run:
  deadline: 10m
  tests: false

linters:
  enable:
    - goimports

issues:
  exclude-rules:
  - path: zz_generated.deepcopy.go
    linters:
      - goimports
  - path: _test.go
    linters:
    - errcheck
